name: "sipstack.io"
description: ""

domain: aboutsip.github.com
author: Jonas Borjesson
email: jonas@aboutsip.com
title: sipstack.io
sipstackio_version: 0.1.1
pktsio_version: 1.0.5

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
